// Generated by scripts/bake-ghost-model.mjs from Aes's ZBrush export. Do not edit by hand.

export const MODEL_URL = "/models/miracle-ghost.glb";
export const FACE_MAP_URL = "/models/miracle-ghost-face.png";
export const HALO_MAP_URL = "/models/miracle-ghost-halo.png";

/** Model-space size after centering, in world units */
export const MODEL_SIZE = { x: 2.77, y: 3, z: 1.348 };

/** Where the front-projected face map sits in model XY */
export const FACE_RECT = { minX: -0.6245, maxX: 0.6245, minY: -0.1284, maxY: 1.1206 };

/** Each painted eye in model XY, left then right, for blinking */
export const EYES = [
  { cx: -0.1909, cy: 0.573, halfW: 0.022, halfH: 0.4275 },
  { cx: 0.1909, cy: 0.573, halfW: 0.022, halfH: 0.4275 },
] as const;

/** Where the halo map sits in model XY */
export const HALO_RECT = { minX: -2.5, maxX: 2.5, minY: -2.5, maxY: 2.5 };

/** Low points of the hem, where droplets bead and fall */
export const MODEL_DRIP_TIPS: [number, number][] = [[-1.057,-1.165],[-0.515,-0.994],[-0.027,-1.497],[0.51,-0.994],[1.033,-1.165]];
